# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/abdullah/CCPP/AeolusRobotics/Part1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/abdullah/CCPP/AeolusRobotics/Part1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/abdullah/CCPP/AeolusRobotics/Part1/CMakeFiles /home/abdullah/CCPP/AeolusRobotics/Part1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/abdullah/CCPP/AeolusRobotics/Part1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named find

# Build rule for target.
find: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 find
.PHONY : find

# fast build rule for target.
find/fast:
	$(MAKE) -f CMakeFiles/find.dir/build.make CMakeFiles/find.dir/build
.PHONY : find/fast

#=============================================================================
# Target rules for targets named view

# Build rule for target.
view: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 view
.PHONY : view

# fast build rule for target.
view/fast:
	$(MAKE) -f CMakeFiles/view.dir/build.make CMakeFiles/view.dir/build
.PHONY : view/fast

FIND_REGION.o: FIND_REGION.cpp.o
.PHONY : FIND_REGION.o

# target to build an object file
FIND_REGION.cpp.o:
	$(MAKE) -f CMakeFiles/find.dir/build.make CMakeFiles/find.dir/FIND_REGION.cpp.o
.PHONY : FIND_REGION.cpp.o

FIND_REGION.i: FIND_REGION.cpp.i
.PHONY : FIND_REGION.i

# target to preprocess a source file
FIND_REGION.cpp.i:
	$(MAKE) -f CMakeFiles/find.dir/build.make CMakeFiles/find.dir/FIND_REGION.cpp.i
.PHONY : FIND_REGION.cpp.i

FIND_REGION.s: FIND_REGION.cpp.s
.PHONY : FIND_REGION.s

# target to generate assembly for a file
FIND_REGION.cpp.s:
	$(MAKE) -f CMakeFiles/find.dir/build.make CMakeFiles/find.dir/FIND_REGION.cpp.s
.PHONY : FIND_REGION.cpp.s

view.o: view.cpp.o
.PHONY : view.o

# target to build an object file
view.cpp.o:
	$(MAKE) -f CMakeFiles/view.dir/build.make CMakeFiles/view.dir/view.cpp.o
.PHONY : view.cpp.o

view.i: view.cpp.i
.PHONY : view.i

# target to preprocess a source file
view.cpp.i:
	$(MAKE) -f CMakeFiles/view.dir/build.make CMakeFiles/view.dir/view.cpp.i
.PHONY : view.cpp.i

view.s: view.cpp.s
.PHONY : view.s

# target to generate assembly for a file
view.cpp.s:
	$(MAKE) -f CMakeFiles/view.dir/build.make CMakeFiles/view.dir/view.cpp.s
.PHONY : view.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... find"
	@echo "... rebuild_cache"
	@echo "... view"
	@echo "... FIND_REGION.o"
	@echo "... FIND_REGION.i"
	@echo "... FIND_REGION.s"
	@echo "... view.o"
	@echo "... view.i"
	@echo "... view.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

